base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
urlpatterns = [
    path("", include("home.urls")),
    path("", include("country.urls")),
    path("", include("job.urls")),
    path("", include("user.urls")),

    path("admin/", admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

country/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:pk>/', views.country, name='country_jobs'),
    path('countries/', views.countries, name='countries'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('service/<int:pk>', views.service),
    path('serve/<int:pk>', views.serve),
    path('about/', views.about),
    path('survey/', views.survey),
    path('our-clients/', views.our_client),
    path('our-strength/', views.our_strength),
    path('corporate-structure/', views.corporate_structure),
    path('management-team/', views.team_management),
    path('recruitment-process/', views.recruitment_process),
    path('quick-register/', views.quick_register),
    path('terms/', views.quick_register),

]

job/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<int:country_pk>/<int:job_pk>/', views.job_details, name='job_details'),
    path('apply-job/<int:job_pk>', views.apply_resume, name='apply_resume'),
    path('apply-job/submit/<int:job_pk>/', views.apply_resume_summit, name='apply_resume_submit'),
    path('success/', views.success, name='success'),
    path('jobseeker/', views.candidate, name='jobseeker'),
    path('clients/', views.clients, name='clients'),
    path('clients/submit', views.clients_submit, name='clients_submit'),

    path('jobseeker/submit', views.candidate_submit, name='jobseeker_submit'),
    path('employee/', views.employee, name='employee'),
    path('employee/submit', views.employee_submit, name='employee_submit'),
    path('study/', views.study, name='study'),
    path('study/submit', views.study_submit, name='study_submit'),
    path('grievance-redressal/', views.grievance, name='grievance'),
    path('grievance-redressal/submit', views.grievance_submit, name='grievance_submit'),
    path('careers', views.createJobList, name='careers_job_list'),
    path('careers/<int:job_pk>', views.job_detailsViewLoggedIn, name='job_detailsViewLoggedIn'),
    path('careers/apply/<int:job_pk>', views.apply_resumeViewLoggedIn, name='apply_resumeViewLoggedIn'),
    path('save/<int:job_pk>', views.save_job_view, name='save_job_view'),
    path('application/', views.application, name='application'),
    path('save/', views.save, name='save'),
    path('update-picture/', views.update_profile_picture , name="update_profile_picture" )
]

country/models.py
from django.db import models
from django.utils import timezone
from utils.validator import  validate_file_size
from django.core.validators import FileExtensionValidator

# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=250)
    banner = models.FileField(upload_to='general/',
    validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size] )
    flag = models.FileField(upload_to='general/',
    validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png','svg']), validate_file_size] )
    created = models.DateTimeField(default=timezone.now)
    
    CONTINENT_CHOOSE = [
        ("asia", "Asia"),
        ("europe", "Europe"),
        ("middle_east", "Middle East"),
    ]
    continent = models.CharField(choices=CONTINENT_CHOOSE, max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name

home/models.py
from django.db import models
from django.db import migrations
from utils.validator import  validate_file_size
from django.core.validators import FileExtensionValidator

# Create your models here.

class Slider(models.Model):
    img = models.FileField(upload_to='general/',   validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    link = models.URLField(max_length=300)
    def __str__(self):
        return f"{self.id} - {self.title}"

class Award(models.Model):
    img = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    title = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.id} - {self.title}"

class Video(models.Model):
    url = models.URLField(max_length=300)
    title = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.id} - {self.title}"




class Serve(models.Model):
    img = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), validate_file_size])
    title = models.CharField(max_length=100)
    banner = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    details_title = models.CharField(max_length=100)
    details = models.TextField(max_length=2000)
    side_Img = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    carousel = models.TextField(max_length=2000)
    options = models.TextField(max_length=2000)

    def __str__(self):
        return f"{self.id} - {self.title}"



class Service(models.Model):
    icon = models.CharField(max_length=300)
    title = models.CharField(max_length=100)
    banner = models.FileField(upload_to='general/',
     validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size]
    )


    details = models.TextField(max_length=2000)
    side_Img = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    
    details2 = models.TextField(null=True , blank=True, max_length=2000)
    side_Img2 = models.FileField(null=True , blank=True, upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    image = models.FileField(null=True , blank=True, upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])

    def __str__(self):
        return f"{self.id} - {self.title}"


class CadidateRegistion(models.Model):
    whatsApp=models.CharField(max_length=15)
    phone=models.CharField(max_length=15)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    position=models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    location = models.CharField(max_length=100)
    resume = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.id} - {self.name}"


class Contact(models.Model):
    phone=models.CharField(max_length=15)
    email = models.EmailField(max_length=100)
    whatsApp=models.CharField(max_length=15)
    fb = models.URLField(max_length=300,default="#")
    fb_group = models.URLField(max_length=300,default="#")
    x = models.URLField(max_length=300,default="#")
    linkedin = models.URLField(max_length=300,default="#")
    youtube = models.URLField(max_length=300,default="#")
    whatsAppLink = models.URLField(max_length=300,default="#")
    location = models.TextField(max_length=250)
    qr_code = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    def __str__(self):
        return self.email


class Setting(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField(max_length=500)
    logo = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    termsAndCondition = models.TextField(max_length=500000)
    def __str__(self):
        return self.title



class Team(models.Model):
    name = models.CharField(max_length=500)
    title = models.CharField(max_length=500)
    text = models.TextField(max_length=1000)
    photo = models.FileField(upload_to='general/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), validate_file_size])
    phone = models.CharField(max_length=250, null=True, blank=True)
    email = models.CharField(max_length=250)
    
    def __str__(self):
        return f"{self.id} - {self.name}"

job/models.py
from django.db import models
from country.models import Country
from utils.validator import  validate_file_size
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from job.position import positions
 

class Job(models.Model):
    title = models.CharField(max_length= 250)
    posted=models.DateField(auto_created=True, auto_now_add=True)
    JOB_TYPE_CHOOSE = [
        ("full_time", "Full Time"),
        ("part_time", "Part Time"),
        ("remote", "Remote"),
    ]
    job_type = models.CharField(choices=JOB_TYPE_CHOOSE,max_length=250, default="full_time")
    city=models.CharField(max_length=250)
    state=models.CharField(max_length=250)
    experience = models.CharField(max_length=250)
    zip_code=models.CharField(max_length=250)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='jobs')
    description=models.TextField(max_length=5000)
    
    def __str__(self):
        return self.title


class ApplyJob(models.Model):
    name = models.CharField(max_length=250)
    designation = models.CharField(max_length=250)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=15)
    age = models.CharField(max_length=15)
    skills = models.TextField(max_length=450)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='apply_job')
    resume = models.FileField(upload_to='resumes/',
    validators=[FileExtensionValidator(allowed_extensions=['pdf']), validate_file_size],
    blank=True,  # Allow form submission without resume
    null=True    # Store null in the database if no file is provide
    ) 
    coverLetter = models.FileField(upload_to='coverLetters/',validators=[FileExtensionValidator(allowed_extensions=['pdf']), validate_file_size],
    blank=True,  # Allow form submission without resume
    null=True    # Store null in the database if no file is provide
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications',blank=True ,  null=True  )

    def __str__(self):
        return self.name

class Client(models.Model):
    first = models.CharField(max_length=250)
    last = models.CharField(max_length=250)
    phone = models.CharField(max_length=250, blank=True, null=True)
    email = models.EmailField(max_length=250,blank=True, null=True )
    companyName = models.CharField(max_length=250, blank=True, null=True)
    position = models.CharField(max_length=250, blank=True, null=True)
    # resume = models.FileField(upload_to='resumes/',
    # validators=[FileExtensionValidator(allowed_extensions=['pdf']), validate_file_size],
    # blank=True, null=True 
    # )
    comment = models.TextField(max_length=5000,blank=True, null=True)


class CurrentLocation(models.Model):
    location = models.CharField(max_length=250)
    def __str__(self):
        return f"{self.id} - {self.location}"

class Candidate(models.Model):
    agreed = models.CharField(max_length=250, null=True, blank=True)
    name = models.CharField(max_length=250)
    phone = models.CharField(max_length=250, blank=True, null=True)
    whatsApp = models.CharField(max_length=250)
    email = models.EmailField(max_length=250,blank=True, null=True )
    exp2 = models.CharField(max_length=250,blank=True, null=True)
    exp = models.CharField(max_length=250,blank=True, null=True)

    
    CATEGORY = {
        'CIVIL':"Civil",
        'MECHANICAL':"Mechanical",
        'ELECTRIAL':"Electrial",
        'IT':"It",
        'INSTRUMENTATION':"Instrumentation",
        'ADMIN':"Admin/HR",
        'SAFETY':"Safety",
        'STAFF':"Project/Planning/Staff",
        'DESIGN':"Design",
        'HEALTHCARE':"Healthcare",
        'HOSPITALITY':"Hospitality",
        'SECURITY':"Security",
        'LOGISTICS':"Logistics",
        'OPERATORS':"Operators/Drivers",
        'OTHER':"Other",
    }
    
    category = models.CharField( choices=CATEGORY, default='OTHER', max_length=250,  blank=True, null=True)
    JOB_POSITION = positions
   
    position = models.CharField(choices=JOB_POSITION, max_length=250)
    location = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='candition_location',  blank=True, null=True)
    currentLocation =  models.ForeignKey(CurrentLocation, on_delete=models.CASCADE, related_name='candition_CurrentLocation',  blank=True, null=True)
    resume = models.FileField(upload_to='resumes/',
    validators=[FileExtensionValidator(allowed_extensions=['pdf']), validate_file_size],
    blank=True, null=True 
    )
    def __str__(self):
            return self.name

class Employee(models.Model):
    name = models.CharField(max_length=250)    
    phone = models.CharField(max_length=250)
    email = models.EmailField(max_length=250, )
    companyName = models.CharField(max_length=250)   
    position = models.CharField(max_length=250)    
    requirement = models.TextField(max_length=250) 
    def __str__(self):
                return self.name


class Study(models.Model):
    firstName = models.CharField(max_length=250)   
    lastName = models.CharField(max_length=250)    
    phone = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    age = models.CharField(max_length=100)
    location = models.CharField(max_length=250)   
    IELTS_CHOICES = [
        ('YES','Yes'),
        ('NO','No'),
    ]
    position = models.CharField(max_length=250)   
    ielts = models.CharField(max_length=100, choices=IELTS_CHOICES)
    def __str__(self):
                return self.name


class Grievance(models.Model):
    name = models.CharField(max_length=250)    
    phone = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=250)   
    remarks  = models.TextField(max_length=250)   
    def __str__(self):
                return self.name



class Save(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='save_user')
    job =  models.ForeignKey(Job, on_delete=models.CASCADE, related_name='jobs_save')

country/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse
from .models import Country as CountryModel
from django.views.decorators.http import require_http_methods
from home.models import Slider, Award, Video, Serve, Contact, Setting, Service
# Create your views here.


def country(request, pk):
    query = request.GET.get("job_search","")
    country = get_object_or_404(CountryModel, id=pk)
    contact = Contact.objects.get(id=1)
    settings = Setting.objects.get(id=1)
    services = Service.objects.all()
    countries = CountryModel.objects.all()
    
    if query:
        jobs = country.jobs.filter(title__icontains= query) 
    else:
        jobs = country.jobs.all() 
    for job in jobs:
            job.split_job_type = f"{job.job_type.split('_')[0]} {job.job_type.split('_')[1]}"

            
    context= {
        'country': country,
        'jobs':jobs,
        'contact':contact,
        'settings':settings,
        'services':services,
        'countries':countries
    }
    return render(request, 'country.html',context)



@require_http_methods(['GET'])
def countries(request):
    contact = Contact.objects.get(id=1)
    settings = Setting.objects.get(id=1)
    services = Service.objects.all()
    countries = CountryModel.objects.all()

    return render(request, 'countries.html',{
        'contact':contact,
        'settings':settings,
        'services':services,
        'countries':countries
    })

templates/apply_job.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} 
{{ settings.title }} 
{% endblock %} 
{% block content %}


    <section class="mx-5">
      <div class="container m-auto flex justify-center">
        <div class="w-full max-w-4xl bg-white p-6 rounded shadow-md px-10 my-8">
          <h1 class="text-2xl mt-3 mb-5 text-center font-serif font-bold">
            Apply for Job
          </h1>

          <form
            method="POST"
            action="{% url 'apply_resume_submit' job.id %}"
            enctype="multipart/form-data"
            class="flex flex-col gap-5"
          >
            {% csrf_token %} {{ form.as_p }}

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_name">Name:</label>
              <input
                type="text"
                name="name"
                maxlength="250"
                required=""
                id="id_name"
                placeholder="Enter you name"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_designation"
                >Designation:</label
              >
              <input
                type="text"
                name="designation"
                maxlength="15"
                required=""
                id="id_designation"
                placeholder="Enter you designation"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_email">Email:</label>
              <input
                type="email"
                name="email"
                maxlength="100"
                required=""
                id="id_email"
                placeholder="Enter you email"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_phone">Phone:</label>
              <input
                type="text"
                name="phone"
                maxlength="15"
                required=""
                id="id_phone"
                placeholder="Enter you phone"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_age">Age:</label>
              <input
                type="text"
                name="age"
                maxlength="15"
                required=""
                id="id_age"
                placeholder="Enter you age"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_skills"
                >Skills:</label
              >
              <textarea
                name="skills"
                cols="40"
                rows="2"
                maxlength="250"
                required=""
                id="id_skills"
                placeholder="Enter you skills"
              ></textarea>
            </p>

            <p class="flex flex-col">
              <label class="font-serif mb-1 font-bold" for="id_resume"
                >Resume:</label
              >
              <input
                type="file"
                name="resume"
                required=""
                id="id_resume"
                class="block w-full text-sm text-gray-500 file:mr-4 file:py-1 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold mb-1" for="id_coverLetter"
                >CoverLetter:</label
              >
              <input
                type="file"
                name="coverLetter"
                required=""
                id="id_coverLetter"
                class="block w-full text-sm text-gray-500 file:mr-4 file:py-1 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
              />
            </p>
            <div class="flex justify-center">
              <button
                class="bg-[#d9534f] hover:bg-primary rounded font-sans text-sm px-3 py-2 text-white w-40"
                type="submit"
              >
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>
    </section>

{% endblock %}

templates/employee.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} 
{{ settings.title }} 
{% endblock %} 
{% block content %}


    <section class="mx-5">
      <div class="container m-auto flex justify-center">
        <div class="w-full max-w-4xl bg-white p-6 rounded shadow-md px-10 my-8">
          <h1 class="text-2xl mt-3 mb-5 text-center font-serif font-bold">
            CANDIDATE REGISTRATION FORM
          </h1>
          <form
            method="POST"
            enctype="multipart/form-data"
            action="{% url 'employee_submit' %}"
            class="flex flex-col gap-5"
          >
            {% csrf_token %} {{ form.as_p }}
            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_name">Name:</label>
              <input
                type="text"
                name="name"
                maxlength="250"
                required=""
                id="id_name"
                placeholder="Enter you name"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_phone">Phone:</label>
              <input
                type="text"
                name="phone"
                maxlength="15"
                required=""
                id="id_phone"
                placeholder="Enter you phone"
              />
            </p>
            <p class="flex flex-col">
              <label class="font-serif font-bold" for="id_email">Email:</label>
              <input
                type="email"
                name="email"
                required=""
                id="id_email"
                placeholder="Enter you email"
              />
            </p>
            <p class="flex flex-col">
              <label class="font-serif font-bold" for="whatsApp"
                >WhatsApp:</label
              >
              <input
                type="text"
                name="whatsApp"
                maxlength="15"
                required=""
                id="whatsApp"
                placeholder="Enter you whatsApp number"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="companyName"
                >Company Name:</label
              >
              <input
                type="text"
                name="companyName"
                maxlength="100"
                required=""
                id="companyName"
                placeholder="Enter you company Name"
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="whatsApp"
                >Position:</label
              >
              <input
                type="text"
                name="position"
                maxlength="15"
                required=""
                id="position"
                placeholder="Enter you position "
              />
            </p>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="requirement"
                >Requirement:</label
              >
              <textarea
                name="requirement"
                cols="40"
                rows="2"
                maxlength="250"
                required=""
                id="requirement"
                placeholder="Enter you requirement"
              ></textarea>
            </p>

            <div class="flex justify-center">
              <button
                class="bg-[#d9534f] hover:bg-primary rounded font-sans text-sm px-3 py-2 text-white w-40"
                type="submit"
              >
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>
    </section>

    <section class="mx-5">
      <div class="container m-auto my-10">
        <h3 class="text-xl my-3 font-serif font-bold">Our Office</h3>

        <div>
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d294.3840949801742!2d90.37921826417632!3d23.809922603040054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c72a05e72f27%3A0x253c8e0afb0d412!2sUmmul%20Qura%20Alia%20Madrasha!5e1!3m2!1sen!2sbd!4v1726599805259!5m2!1sen!2sbd"
            height="450"
            style="border: 0; width: 100%"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </div>
    </section>

{% endblock %}

templates/grievance.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} 
{{ settings.title }} 
{% endblock %} 
{% block content %}


    <section class="mx-5">
      <div class="container m-auto flex justify-center">
        <div class="w-full max-w-4xl bg-white p-6 rounded shadow-md px-10 my-8">
          <h1
            class="md:text-3xl text-xl mt-3 mb-5 text-center font-serif font-bold"
          >
            Grievance Redressal Form
          </h1>
          <p class="my-4 text-red-500 text-2xl font-semibold">
            Have any issues in working with our Agency or our Clients? Please
            use the form below to write to us explaining the details of the
            grievance and we will promptly forward this to the relevant
            authorities
          </p>
          <form
            method="POST"
            enctype="multipart/form-data"
            action="{% url 'grievance_submit' %}"
            class="flex flex-col gap-5"
          >
            {% csrf_token %} {{ form.as_p }}
            <div class="flex flex-col">
              <label for="id_name" class="font-serif font-bold">Name:</label>
              <input
                type="text"
                name="name"
                maxlength="250"
                required
                id="id_name"
              />
            </div>

            <div class="flex flex-col">
              <label for="id_phone" class="font-serif font-bold">Phone:</label>
              <input
                type="text"
                name="phone"
                maxlength="250"
                required
                id="id_phone"
              />
            </div>
            <div class="flex flex-col">
              <label for="id_email" class="font-serif font-bold">Email:</label>
              <input
                type="email"
                name="email"
                maxlength="250"
                required
                id="id_email"
              />
            </div>
            <div class="flex flex-col">
              <label for="id_title" class="font-serif font-bold">Title:</label>
              <input
                type="text"
                name="title"
                maxlength="100"
                required
                id="id_title"
              />
            </div>
            <div class="flex flex-col">
              <label for="id_location" class="font-serif font-bold"
                >Location:</label
              >
              <input
                type="text"
                name="location"
                maxlength="250"
                required
                id="id_location"
              />
            </div>
            <div class="flex flex-col">
              <label for="id_position" class="font-serif font-bold"
                >Position:</label
              >
              <input
                type="text"
                name="position"
                maxlength="250"
                required
                id="id_position"
              />
            </div>

            <p class="flex flex-col">
              <label class="font-serif font-bold" for="remarks">Remarks:</label>
              <textarea
                name="remarks"
                cols="40"
                rows="2"
                maxlength="250"
                required=""
                id="remarks"
                placeholder="Enter you remarks"
              ></textarea>
            </p>
            <div class="flex justify-center">
              <button
                class="bg-[#d9534f] hover:bg-primary rounded font-sans text-sm px-3 py-2 text-white w-40"
                type="submit"
              >
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>
    </section>

    <section class="mx-5">
      <div class="container m-auto my-10">
        <h3 class="text-xl my-3 font-serif font-bold">Our Office</h3>

        <div>
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d294.3840949801742!2d90.37921826417632!3d23.809922603040054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c72a05e72f27%3A0x253c8e0afb0d412!2sUmmul%20Qura%20Alia%20Madrasha!5e1!3m2!1sen!2sbd!4v1726599805259!5m2!1sen!2sbd"
            height="450"
            style="border: 0; width: 100%"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </div>
    </section>

{% endblock %}

templates/terms.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ settings.title }}
{% endblock %}
{% block content %}


<section
  class="md:h-[400px] h-[180px] flex items-center justify-center w-full bg-cover	bg-no-repeat bg-[url({% static 'images/innerpage-banners/terms-and-conditions.jpg'%})]">
  <h1 style="text-shadow: 2px 2px #000"
    class="md:text-5xl text-3xl [text-shadow:_0_1px_0_rgb(0_0_0_/_40%)] text-white font-serif font-bold">
    Terms and Conditions

  </h1>
</section>

<section class="mx-5">
  <div class="container m-auto py-10">
    {{settings.termsAndCondition|safe}}
  </div>
</section>

<section class="mx-5">
  <div class="container m-auto my-10">
    <h3 class="text-xl my-3 font-serif font-bold">Our Office</h3>

    <div>
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d294.3840949801742!2d90.37921826417632!3d23.809922603040054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c72a05e72f27%3A0x253c8e0afb0d412!2sUmmul%20Qura%20Alia%20Madrasha!5e1!3m2!1sen!2sbd!4v1726599805259!5m2!1sen!2sbd"
        height="450" style="border: 0; width: 100%" allowfullscreen="" loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
</section>

{% endblock %}